---
new_page_extension: md
auto_deploy: true
admin_path: static/admin/
webhook_url: 
sections:
- type: directory
  path: site/content/products
  label: Products
  create: all
  match: "**/*"
  templates:
  - products
upload_dir: site/static/uploads
public_path: static/uploads
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: false
build:
  preview_env:
  - HUGO_ENV=default
  - HUGO_VERSION=0.38.1
  preview_output_directory: "/public"
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.38.1
  output_directory: "/public"
  preview_command: hugo -E -F -D -d public
version: 0.38.1
