---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: site/content/products
  label: Products
  create: all
  match: "**/*"
  templates:
  - products
upload_dir: snipcart-hugo-demo
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: hugo
  publish_command: hugo
  output_directory: site/public
version: 0.38.1
