---
new_page_extension: md
auto_deploy: true
admin_path: static/admin/
webhook_url: 
sections:
- type: directory
  path: site/content/products
  label: Products
  create: all
  match: "**/*"
  templates:
  - products
upload_dir: snipcart-hugo-demo
public_path: static/uploads
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -d public
  publish_command: hugo -d public
  output_directory: "/public"
version: 0.38.1
