# Site settings
# --------------
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ .Site.Params.myvariable }}.            baseURL = "https://<YOUR-USER-NAME>.github.io/"
baseurl = "/" # The subpath of your site, e.g. / or /blog    ЭТО САЙТ  zen-hamilton-8f9187.netlify.com
languageCode = "ru"  #или тут
languageLang = "ru"      #здесь язык для снипкарт и сайта вообще
defaultContentLanguage = "ru"  #или здесь
title = "Доставка Корейских Блюд"

# Build settings
# --------------

# Set the destination the same as the Gulpfile for consistency
destination = "../dist/"

# Categories and tags disabled for an easier start
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]

# Enable this to have links relativized by Hugo
# E.g,  if your /post/first/ page contains a link
# to /about/, Hugo will rewrite the URL to ../../about/
relativeURLs = false

# Enable to have links open in new tab
hrefTargetBlank = false

# Enable rendering of Emojis in markdown
enableEmoji = true

# Site Params
# -------------
[params]
description = '''
Многие в нашем городе любят Корейскую кухню 🍛
Но не везде её правильно и вкусно готовят 😕
Мы предлагаем Вам большой выбор, начиная от салатов 🥗 до горячих блюд 🥘
Вкусно, качественно и по приемлемым ценам ✔️
В этом Вы можете убедиться лично, сделав заказ 📝

'''
author = "cook_son34"
currency = "₽"
#тут оба нужны а чтоб работал еще в снипкарте прикрепить его в домены чтоб он проверялся всегда там сам
snipcart_test_api_key = "MGQzMWVkMmYtMzhlZC00MjU4LTk3MjQtZDNmMzM1MTI1ZDlhNjM1OTY4NjY2NjE5MTAwMzMy"
snipcart_live_api_key = "MGQzMWVkMmYtMzhlZC00MjU4LTk3MjQtZDNmMzM1MTI1ZDlhNjM1OTY4NjY2NjE5MTAwMzMy" # два тест ключа
cloudinary_base_url = "https://res.cloudinary.com/dnyfubwui"

[taxonomies]
  category = "categories"
